name: Node.js CI

on:
  push:
    branches:
- main
  pull_request:
    branches:
- main 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
- main: Checkout repository
      uses: actions/checkout@v3

- main: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

- main: Install dependencies
      run: npm install --legacy-peer-deps

- main: Start application
      run: npm start
